import Head from "next/head";
import { useEffect, useState } from "react";
import { Typewriter } from "react-simple-typewriter";

export default function Home() {
  const [openingAnimation, setAnimation] = useState(true);
  useEffect(() => {
    const timer = setTimeout(() => {
      setAnimation(() => false);
    }, 2000);
    return () => clearTimeout(timer);
  }, []);
  const handleType = (count: number) => {};

  const handleDone = () => {
    console.log(`Done after 5 loops!`);
  };

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by Portfolio" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {openingAnimation && (
          <div className="loader">
            <div className="left-loader"></div>
            <div className="right-loader"></div>
          </div>
        )}

        <div className="main-wrapper flex flex-col justify-center align-center relative w-full h-full">
          <div className="w-full h-72 text-center text-white flex flex-row justify-center align-center">
            <img
              src="https://img.freepik.com/premium-vector/portrait-young-man-with-beard-hair-style-male-avatar-vector-illustration_266660-423.jpg?w=2000"
              alt=""
              className="w-48 h-48 p-1 rounded-full ring-2 ring-yellow-300"
            />
            <div className="flex flex-col ml-10 w-72">
              <h1 className="text-3xl">Hi There!</h1>
              <div className="text-3xl [&>span]:text-3xl [&>span]:text-yellow-300">
                I'm a 
                <Typewriter
                  words={[" Eat", " Sleep", " Code", " Repeat!"]}
                  loop={Infinity}
                  cursor
                  cursorStyle="_"
                  typeSpeed={70}
                  deleteSpeed={50}
                  delaySpeed={1000}
                  onLoopDone={handleDone}
                  onType={handleType}
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
